version: "3"

services:
  #  TODO: setup internal docker containers
  #  app:
  #    container_name: task-app
  #    build:
  #      context: apps/api-server
  #      dockerfile: apps/api-server/Dockerfile
  #    environment:
  #      - APP_PORT=3000
  #    ports:
  #      - "3000:${APP_PORT}"

  mongo_db:
    container_name: task-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_task_db_data:/data/db

volumes:
  mongodb_task_db_data:
